gui:
  theme:
    activeBorderColor:
      - "#c98c5a"
      - bold

    inactiveBorderColor:
      - "#817264"

    searchingActiveBorderColor:
      - "#c98c5a"
      - bold

    optionsTextColor:
      - "#c98c5a"

    selectedLineBgColor:
      - "#3a312a"

    defaultFgColor:
      - "#d8c8a8"

    unstagedChangesColor:
      - "#b85c4d"

    cherryPickedCommitFgColor:
      - "#c98c5a"

    cherryPickedCommitBgColor:
      - "#3a312a"

    branchColor:
      - "#6d7d8c"

    remoteBranchColor:
      - "#c98c5a"

    headColor:
      - "#b85c4d"
      - bold
