#!/usr/bin/env bash

THEMES_DIR="$HOME/.config/themes/colors"
CURRENT_THEME="$HOME/.config/themes/current"

#Create Current if it doesn't exist
mkdir -p "$(dirname "$CURRENT_THEME")"

# Enable nullglob so empty directories don't return literal '*.conf'
shopt -s nullglob

# Get available themes
themes=("$THEMES_DIR"/*.conf)
theme_names=()

for theme in "${themes[@]}"; do
  name=$(basename "$theme" .conf)
  theme_names+=("$name")
done

# Show theme selection menu
selected=$(printf "%s\n" "${theme_names[@]}" | rofi -dmenu -p -i "Select Theme" -theme-str '
    window {
        width: 20%;
    }
    listview {
        lines: 6;
        fixed-height: true;
      }')

if [[ -z "$selected" ]]; then
  exit 0
fi

# Find the selected theme file
selected_file="$THEMES_DIR/${selected}.conf"

if [[ ! -f "$selected_file" ]]; then
  echo "Theme file not found: $selected_file"
  exit 1
fi

# Super simple color extractor (no spaces after =)
get_color() {
  local theme_file="$1"
  local color_name="$2"
  grep "^$color_name=" "$theme_file" |
    cut -d= -f2
}

# Convert hex to Hyprland RGBA format
hex_to_rgba() {
  local hex="$1"
  echo "rgba(${hex}ff)"
}

# Globally defined color values (One time file read to get colors)
# Base colors
background=$(get_color "$selected_file" "background")
foreground=$(get_color "$selected_file" "foreground")
background_alt=$(get_color "$selected_file" "background_alt")
background_dim=$(get_color "$selected_file" "background_dim")
foreground_dim=$(get_color "$selected_file" "foreground_dim")
cursor=$(get_color "$selected_file" "cursor")

# Accent colors
accent=$(get_color "$selected_file" "accent")
accent_alt=$(get_color "$selected_file" "accent_alt")

# Status colors
error=$(get_color "$selected_file" "error")
warning=$(get_color "$selected_file" "warning")
success=$(get_color "$selected_file" "success")
info=$(get_color "$selected_file" "info")
orange=$(get_color "$selected_file" "orange")
bright_orange=$(get_color "$selected_file" "bright_orange")

# UI colors
selection=$(get_color "$selected_file" "selection")
border=$(get_color "$selected_file" "border")
background_highlight=$(get_color "$selected_file" "background_highlight")
overlay=$(get_color "$selected_file" "overlay")

# Standard 16-color palette
black=$(get_color "$selected_file" "black")
red=$(get_color "$selected_file" "red")
green=$(get_color "$selected_file" "green")
yellow=$(get_color "$selected_file" "yellow")
blue=$(get_color "$selected_file" "blue")
magenta=$(get_color "$selected_file" "magenta")
cyan=$(get_color "$selected_file" "cyan")
white=$(get_color "$selected_file" "white")

bright_black=$(get_color "$selected_file" "bright_black")
bright_red=$(get_color "$selected_file" "bright_red")
bright_green=$(get_color "$selected_file" "bright_green")
bright_yellow=$(get_color "$selected_file" "bright_yellow")
bright_blue=$(get_color "$selected_file" "bright_blue")
bright_magenta=$(get_color "$selected_file" "bright_magenta")
bright_cyan=$(get_color "$selected_file" "bright_cyan")
bright_white=$(get_color "$selected_file" "bright_white")

# Grayscale
gray1=$(get_color "$selected_file" "gray1")
gray2=$(get_color "$selected_file" "gray2")
gray3=$(get_color "$selected_file" "gray3")
gray4=$(get_color "$selected_file" "gray4")
gray5=$(get_color "$selected_file" "gray5")
gray6=$(get_color "$selected_file" "gray6")
gray7=$(get_color "$selected_file" "gray7")

generate_lazygit_theme() {

  cat <<EOF
gui:
  theme:
    activeBorderColor:
      - "#$accent"
      - bold

    inactiveBorderColor:
      - "#$gray6"

    searchingActiveBorderColor:
      - "#$accent"
      - bold

    optionsTextColor:
      - "#$accent"

    selectedLineBgColor:
      - "#$selection"

    defaultFgColor:
      - "#$foreground"

    unstagedChangesColor:
      - "#$error"

    cherryPickedCommitFgColor:
      - "#$accent"

    cherryPickedCommitBgColor:
      - "#$background_highlight"

    branchColor:
      - "#$accent_alt"

    remoteBranchColor:
      - "#$accent"

    headColor:
      - "#$error"
      - bold
EOF

}

# Mako - Notification Daemon
generate_mako_colors() {

  cat <<EOF
# Auto-generated by theme switcher

# --- Base Styling ---
background-color=#$background
text-color=#$foreground
border-color=#$border
progress-color=#$accent

# --- Urgency Levels ---

[urgency=low]
border-color=#$info

[urgency=normal]
border-color=#$border

[urgency=high]
border-color=#$error
text-color=#$error
EOF
}

# Generate Rofi colors (stays with hex)
generate_rofi_colors() {

  cat <<EOF
* {
    background: #$background;
    foreground: #$foreground;
    background-alt: #$background_alt;
    accent: #$accent;
    accent-alt: #$accent_alt;
    border: #$border;
    warning: #$warning;
    error: #$error;
    success: #$success;
    info: #$info;
    selected: #$selection;
    gray1: #$gray1;
    gray2: #$gray2;
    gray3: #$gray3;
    gray4: #$gray4;
    gray5: #$gray5;
    gray6: #$gray6;
    gray7: #$gray7;
    background-dim: #$background_dim;
    foreground-dim: #$foreground_dim;
    background-highlight: #$background_highlight;
}
EOF
}

#Generate Foot Colors
generate_foot_colors() {
  cat <<EOF
[colors-dark]
background=$background
foreground=$foreground

selection-background=$selection
selection-foreground=$foreground

cursor=$background $accent

regular0=$black
regular1=$red
regular2=$green
regular3=$yellow
regular4=$blue
regular5=$magenta
regular6=$cyan
regular7=$white

bright0=$bright_black
bright1=$bright_red
bright2=$bright_green
bright3=$bright_yellow
bright4=$bright_blue
bright5=$bright_magenta
bright6=$bright_cyan
bright7=$bright_white
EOF
}

generate_nvim_colors() {

  cat <<EOF
-- Auto-generated from $(basename "$theme_file")
return {
    -- Base / Core tones
    bg        = "#$background",
    bg_alt    = "#$background_alt",
    bg_dim    = "#$background_dim",
    fg        = "#$foreground",
    fg_dim    = "#$foreground_dim",
    cursor    = "#$cursor",

    -- Accent / highlights
    accent          = "#$accent",
    accent_alt        = "#$accent_alt",

    -- Status / semantic
    error             = "#$error",
    warning           = "#$warning",
    success           = "#$success",
    info              = "#$info",
    orange            = "#$orange",
    bright_orange     = "#$bright_orange",

    -- UI / structural
    selection         = "#$selection",
    border            = "#$border",
    background_highlight = "#$background_highlight",
    overlay           = "#$overlay",

    -- Standard 16-color palette
    black             = "#$black",
    red               = "#$red",
    green             = "#$green",
    yellow            = "#$yellow",
    blue              = "#$blue",
    magenta           = "#$magenta",
    cyan              = "#$cyan",
    white             = "#$white",

    bright_black      = "#$bright_black",
    bright_red        = "#$bright_red",
    bright_green      = "#$bright_green",
    bright_yellow     = "#$bright_yellow",
    bright_blue       = "#$bright_blue",
    bright_magenta    = "#$bright_magenta",
    bright_cyan       = "#$bright_cyan",
    bright_white      = "#$bright_white",

    -- Grayscale
    gray1             = "#$gray1",
    gray2             = "#$gray2",
    gray3             = "#$gray3",
    gray4             = "#$gray4",
    gray5             = "#$gray5",
    gray6             = "#$gray6",
    gray7             = "#$gray7",
}
EOF
}

generate_btop_colors() {

  cat <<EOF
# Auto-generated from $(basename "$theme_file")
# Main background
theme[main_bg]="#$background"

# Main text color
theme[main_fg]="#$foreground"

# Title color for boxes
theme[title]="#$accent"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#$orange"

# Background color of selected items
theme[selected_bg]="#$selection"

# Foreground color of selected items
theme[selected_fg]="#$foreground"

# Color of inactive/disabled text
theme[inactive_fg]="#$foreground_dim"

# Color of text appearing on top of graphs
theme[graph_text]="#$foreground"

# Misc colors for processes box
theme[proc_misc]="#$foreground"

# Cpu box outline color
theme[cpu_box]="#$accent"

# Memory/disks box outline color
theme[mem_box]="#$accent"

# Net up/down box outline color
theme[net_box]="#$accent"

# Processes box outline color
theme[proc_box]="#$accent"

# Box divider line and small boxes line color
theme[div_line]="#$accent"

# Temperature graph colors
theme[temp_start]="#$green"
theme[temp_mid]="#$yellow"
theme[temp_end]="#$orange"

# CPU graph colors
theme[cpu_start]="#$cyan"
theme[cpu_mid]="#$blue"
theme[cpu_end]="#$accent"

# Mem/Disk free meter
theme[free_start]="#$cyan"
theme[free_mid]="#$blue"
theme[free_end]="#$accent"

# Mem/Disk cached meter
theme[cached_start]="#$cyan"
theme[cached_mid]="#$blue"
theme[cached_end]="#$accent"

# Mem/Disk available meter
theme[available_start]="#$cyan"
theme[available_mid]="#$blue"
theme[available_end]="#$accent"

# Mem/Disk used meter
theme[used_start]="#$cyan"
theme[used_mid]="#$blue"
theme[used_end]="#$accent"

# Download graph colors
theme[download_start]="#$bright_blue"
theme[download_mid]="#$blue"
theme[download_end]="#$bright_cyan"

# Upload graph colors
theme[upload_start]="#$bright_cyan"
theme[upload_mid]="#$green"
theme[upload_end]="#$bright_green"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#$bright_green"
theme[process_mid]="#$bright_yellow"
theme[process_end]="#$bright_red"
EOF
}

generate_yazi_theme() {

  cat <<EOF
# Yazi theme generated from: $theme_name
# Auto-generated by theme switcher

"$schema" = "https://yazi-rs.github.io/schemas/theme.json"

# : Flavor {{{
[flavor]
dark  = ""
light = ""
# : }}}

# : Manager {{{
[mgr]
cwd = { fg = "#$accent" }

# Hovered
hovered         = { bg = "#$accent", fg = "#$background" }
preview_hovered = { fg = "#$accent", underline = true }

# Find
find_keyword  = { fg = "#$accent_alt", bold = true, italic = true, underline = true }
find_position = { fg = "#$accent_alt", bg = "reset", bold = true, italic = true }

# Symlink
symlink_target = { fg = "#$accent", italic = true }

# Marker
marker_copied   = { fg = "#$success", bg = "#$success" }
marker_cut      = { fg = "#$error", bg = "#$error" }
marker_marked   = { fg = "#$info", bg = "#$info" }
marker_selected = { fg = "#$accent", bg = "#$accent" }

# Count
count_copied   = { fg = "#$white", bg = "#$success" }
count_cut      = { fg = "#$white", bg = "#$error" }
count_selected = { fg = "#$white", bg = "#$accent" }

# Border
border_symbol = "│"
border_style  = { fg = "#$border" }

# Highlighting
syntect_theme = ""
# : }}}

# : Tabs {{{
[tabs]
active   = { bg = "#$accent", fg = "#$background", bold = true }
inactive = { fg = "#$accent", bg = "#$background_alt" }

# Separator
sep_inner = { open = "", close = "" }
sep_outer = { open = "", close = "" }
# : }}}

# : Mode {{{
[mode]
normal_main = { bg = "#$accent", fg = "#$background", bold = true }
normal_alt  = { fg = "#$accent", bg = "#$background_alt" }

# Select mode
select_main = { bg = "#$warning", fg = "#$background", bold = true }
select_alt  = { fg = "#$warning", bg = "#$background_alt" }

# Unset mode
unset_main = { bg = "#$error", fg = "#$background", bold = true }
unset_alt  = { fg = "#$error", bg = "#$background_alt" }
# : }}}

# : Status bar {{{
[status]
overall   = { fg = "#$foreground", bg = "#$background_alt" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_sep   = { fg = "#$foreground_dim" }
perm_type  = { fg = "#$success" }
perm_read  = { fg = "#$warning" }
perm_write = { fg = "#$error" }
perm_exec  = { fg = "#$accent" }

# Progress
progress_label  = { fg = "#$accent", bold = true }
progress_normal = { fg = "#$accent", bg = "#$background_highlight" }
progress_error  = { fg = "#$error", bg = "#$background_highlight" }
# : }}}

# : Which {{{
[which]
cols            = 3
mask            = { bg = "#$background_dim" }
cand            = { fg = "#$accent" }
rest            = { fg = "#$foreground_dim" }
desc            = { fg = "#$accent_alt" }
separator       = "  "
separator_style = { fg = "#$border" }
# : }}}

# : Confirmation {{{
[confirm]
border     = { fg = "#$accent" }
title      = { fg = "#$accent", bold = true }
body       = { fg = "#$foreground" }
list       = { fg = "#$foreground" }
btn_yes    = { bg = "#$accent", fg = "#$background", bold = true }
btn_no      = { fg = "#$foreground_dim" }
btn_labels = [ "  [Y]es  ", "  (N)o  " ]
# : }}}

# : Notification {{{
[notify]
title_info  = { fg = "#$success", bold = true }
title_warn  = { fg = "#$warning", bold = true }
title_error = { fg = "#$error", bold = true }

# Icons
icon_info  = ""
icon_warn  = ""
icon_error = ""
# : }}}

# : Picker {{{
[pick]
border   = { fg = "#$accent" }
active   = { fg = "#$accent", bold = true }
inactive = { fg = "#$foreground_dim" }
# : }}}

# : Input {{{
[input]
border   = { fg = "#$accent" }
title    = { fg = "#$accent" }
value    = { fg = "#$foreground" }
selected = { bg = "#$accent", fg = "#$background" }
# : }}}

# : Completion {{{
[cmp]
border   = { fg = "#$accent" }
active   = { bg = "#$accent", fg = "#$background" }
inactive = { fg = "#$foreground" }

# Icons
icon_file    = ""
icon_folder  = ""
icon_command = ""
# : }}}

# : Task manager {{{
[tasks]
border  = { fg = "#$accent" }
title   = { fg = "#$accent" }
hovered = { fg = "#$accent", bold = true }
# : }}}

# : Help menu {{{
[help]
on      = { fg = "#$accent" }
run     = { fg = "#$accent_alt" }
desc    = { fg = "#$foreground" }
hovered = { fg = "#$background", bg = "#$overlay", bold = true }
footer  = { fg = "#$background", bg = "#$accent" }
# : }}}

# : File-specific styles {{{
[filetype]
rules = [
	# Image
	{ mime = "image/*", fg = "#$accent_alt" },
	# Media
	{ mime = "{audio,video}/*", fg = "#$info" },
	# Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#$warning" },
	# Document
	{ mime = "application/{pdf,doc,rtf}", fg = "#$success" },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", fg = "#$foreground_dim" },
	# Special file
	{ url = "*", is = "orphan", bg = "#$error" },
	{ url = "*", is = "exec"  , fg = "#$success" },
	# Dummy file
	{ url = "*", is = "dummy", bg = "#$error" },
	{ url = "*/", is = "dummy", bg = "#$error" },
	# Fallback
	{ url = "*/", fg = "#$accent" }
]
# : }}}
[icon]
prepend_conds = [
	# This targets all directories and gives them your theme's tan color
	{ if = "dir",  text = "", fg = "#$accent" },
]
EOF
}

generate_hyprlock_colors() {
  cat <<EOF
# Auto-generated by theme switcher

\$background = rgb($background)
\$foreground = rgb($foreground)
\$background_alt = rgb($background_alt)
\$background_dim = rgb($background_dim)
\$foreground_dim = rgb($foreground_dim)
\$cursor = rgb($cursor)

\$accent = rgb($accent)
\$accent_alt = rgb($accent_alt)

\$error = rgb($error)
\$warning = rgb($warning)
\$success = rgb($success)
\$info = rgb($info)
\$orange = rgb($orange)
\$bright_orange = rgb($bright_orange)

\$selection = rgb($selection)
\$border = rgb($border)
\$background_highlight = rgb($background_highlight)
\$overlay = rgb($overlay)

\$black = rgb($black)
\$red = rgb($red)
\$green = rgb($green)
\$yellow = rgb($yellow)
\$blue = rgb($blue)
\$magenta = rgb($magenta)
\$cyan = rgb($cyan)
\$white = rgb($white)

\$bright_black = rgb($bright_black)
\$bright_red = rgb($bright_red)
\$bright_green = rgb($bright_green)
\$bright_yellow = rgb($bright_yellow)
\$bright_blue = rgb($bright_blue)
\$bright_magenta = rgb($bright_magenta)
\$bright_cyan = rgb($bright_cyan)
\$bright_white = rgb($bright_white)

\$gray1 = rgb($gray1)
\$gray2 = rgb($gray2)
\$gray3 = rgb($gray3)
\$gray4 = rgb($gray4)
\$gray5 = rgb($gray5)
\$gray6 = rgb($gray6)
\$gray7 = rgb($gray7)
EOF
}

generate_sway_colors() {

  cat <<EOF
# Auto-generated by theme switcher

# Base
set \$background #$background
set \$foreground #$foreground
set \$background_alt #$background_alt
set \$background_dim #$background_dim
set \$foreground_dim #$foreground_dim
set \$cursor #$cursor

# Accent
set \$accent #$accent
set \$accent_alt #$accent_alt

# Status
set \$error #$error
set \$warning #$warning
set \$success #$success
set \$info #$info
set \$orange #$orange
set \$bright_orange #$bright_orange

# UI
set \$selection #$selection
set \$border #$border
set \$background_highlight #$background_highlight
set \$overlay #$overlay

# ANSI colors
set \$black #$black
set \$red #$red
set \$green #$green
set \$yellow #$yellow
set \$blue #$blue
set \$magenta #$magenta
set \$cyan #$cyan
set \$white #$white

set \$bright_black #$bright_black
set \$bright_red #$bright_red
set \$bright_green #$bright_green
set \$bright_yellow #$bright_yellow
set \$bright_blue #$bright_blue
set \$bright_magenta #$bright_magenta
set \$bright_cyan #$bright_cyan
set \$bright_white #$bright_white

# Grays
set \$gray1 #$gray1
set \$gray2 #$gray2
set \$gray3 #$gray3
set \$gray4 #$gray4
set \$gray5 #$gray5
set \$gray6 #$gray6
set \$gray7 #$gray7
EOF

}

## Fuzzel

generate_fuzzel_colors() {
  cat <<EOF
[colors]
background=${background}ff
text=${foreground}ff
match=${warning}ff
selection=${accent}ff
selection-text=${background}ff
selection-match=${warning}ff
border=${border}ff
EOF
}

# Waybar
generate_waybar_colors() {
  cat <<EOF
/* Auto-generated from $(basename "$theme_file") */
@define-color background #$background;
@define-color background_alt #$background_alt;
@define-color background_dim #$background_dim;
@define-color foreground #$foreground;
@define-color foreground_dim #$foreground_dim;
@define-color cursor #$cursor;
@define-color accent #$accent;
@define-color accent_alt #$accent_alt;
@define-color error #$error;
@define-color warning #$warning;
@define-color success #$success;
@define-color info #$info;
@define-color orange #$orange;
@define-color bright_orange #$bright_orange;
@define-color selection #$selection;
@define-color border #$border;
@define-color background_highlight #$background_highlight;
@define-color overlay #$overlay;
@define-color black #$black;
@define-color red #$red;
@define-color green #$green;
@define-color yellow #$yellow;
@define-color orange #$orange;
@define-color blue #$blue;
@define-color magenta #$magenta;
@define-color cyan #$cyan;
@define-color white #$white;
@define-color bright_black #$bright_black;
@define-color bright_red #$bright_red;
@define-color bright_green #$bright_green;
@define-color bright_yellow #$bright_yellow;
@define-color bright_orange #$bright_orange;
@define-color bright_blue #$bright_blue;
@define-color bright_magenta #$bright_magenta;
@define-color bright_cyan #$bright_cyan;
@define-color bright_white #$bright_white;
@define-color gray1 #$gray1;
@define-color gray2 #$gray2;
@define-color gray3 #$gray3;
@define-color gray4 #$gray4;
@define-color gray5 #$gray5;
@define-color gray6 #$gray6;
@define-color gray7 #$gray7;
EOF
}

# Apply theme
apply_theme() {
  local theme_file="$1" # ADDED: Accept the theme file as parameter
  local theme_name=$(basename "$theme_file" .conf)

  echo "Applying theme: $theme_name"

  # Update current theme symlink
  rm -f "$CURRENT_THEME"

  ln -sf "$theme_file" "$CURRENT_THEME"

  # Generate color files (REMOVED parameters since we use global variables)
  generate_sway_colors >~/.config/sway/colors
  generate_lazygit_theme >~/.config/lazygit/config.yml
  generate_fuzzel_colors >~/.config/fuzzel/colors.ini
  generate_hyprlock_colors >~/.config/hypr/colors.conf
  generate_rofi_colors >~/.config/rofi/colors.rasi
  #generate_kitty_colors > ~/.config/kitty/colors.conf
  generate_foot_colors >~/.config/foot/themes/colors.ini
  generate_waybar_colors >~/.config/waybar/colors.css
  generate_mako_colors >~/.config/mako/colors
  #generate_swaync_css > ~/.config/swaync/style.css
  generate_nvim_colors >~/.config/nvim/lua/colors.lua
  generate_btop_colors >~/.config/btop/themes/theme.conf
  #generate_rmpc_theme > ~/.config/rmpc/themes/generatedtheme.ron
  generate_yazi_theme >~/.config/yazi/theme.toml
  # generate_wifitui_theme >~/.config/wifitui/theme.toml

  # Reload applications
  sleep 0.2
  echo "Reloading..."

  #swaync-client -rs
  makoctl reload

  swaymsg reload

  #Custom Wallpaper setter based on theme
  $HOME/.local/bin/set-theme-wallpaper

  #Reload Terminal
  pkill -USR2 foot

  #Reload Waybar
  pkill waybar
  waybar &

  notify-send "Theme Changed" "Applied: $theme_name"
}

apply_theme "$selected_file"
